# Generated by Django 4.0.4 on 2022-04-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_alter_customuser_managers_remove_teacher_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='user_type',
            field=models.CharField(choices=[(1, 'Super_Admin'), (2, 'Teacher'), (3, 'Student')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='super_admin',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='super_admin',
            name='user_type',
            field=models.CharField(choices=[(1, 'Super_Admin'), (2, 'Teacher'), (3, 'Student')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_type',
            field=models.CharField(choices=[(1, 'Super_Admin'), (2, 'Teacher'), (3, 'Student')], default=1, max_length=1),
        ),
    ]
