# Generated by Django 4.0.4 on 2022-04-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_student_name_student_user_type_super_admin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='super_admin',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
