# Generated by Django 4.0.4 on 2022-04-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_student_email_super_admin_email_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='super_admin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='admin',
        ),
    ]
