# Generated by Django 4.0.4 on 2022-04-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_remove_student_admin_remove_super_admin_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
