# Generated by Django 4.0.4 on 2022-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_alter_customuser_managers_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_type',
            field=models.CharField(choices=[(1, 'Super_Admin'), (2, 'Teacher'), (3, 'Student')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_type',
            field=models.CharField(choices=[(1, 'Super_Admin'), (2, 'Teacher'), (3, 'Student')], default=2, max_length=1),
        ),
    ]
